[package]
name = "srml-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition =  "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
runtime_io = { package = "sr-io", path = "../../core/sr-io", default-features = false }
safe-mix = { version = "1.0", default-features = false}
serde = { version = "1.0", optional = true }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
sr-staking-primitives = { path = "../../core/sr-staking-primitives", default-features = false }
srml-support = { path = "../support", default-features = false }
substrate-trie = { path = "../../core/trie", default-features = false, optional = true }
system = { package = "srml-system", path = "../system", default-features = false }
timestamp = { package = "srml-timestamp", path = "../timestamp", default-features = false }

[dev-dependencies]
primitives = { package = "substrate-primitives",  path = "../../core/primitives" }
app-crypto = { package = "substrate-application-crypto",  path = "../../core/application-crypto" }
lazy_static = "1.0"

[features]
default = ["std", "historical"]
historical = ["substrate-trie"]
std = [
	"codec/std",
	"rstd/std",
	"runtime_io/std",
	"safe-mix/std",
	"serde",
	"sr-primitives/std",
	"sr-staking-primitives/std",
	"srml-support/std",
	"substrate-trie/std",
	"timestamp/std",
]
