[package]
name = "substrate-finality-grandpa-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
app-crypto = { package = "substrate-application-crypto", path = "../../application-crypto", default-features = false }
client = { package = "substrate-client", path = "../../client", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
grandpa = { package = "finality-grandpa", version = "0.9.0", features = ["derive-codec"], default-features = false }
rstd = { package = "sr-std", path = "../../sr-std", default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
sr-primitives = { path = "../../sr-primitives", default-features = false }
sr-staking-primitives = { path = "../../sr-staking-primitives", default-features = false }

[features]
default = ["std"]
std = [
	"app-crypto/std",
	"client/std",
	"codec/std",
	"grandpa/std",
	"rstd/std",
	"serde",
	"sr-primitives/std",
	"sr-staking-primitives/std",
]
