[package]
name = "substrate-consensus-babe-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"

[dependencies]
app-crypto = { package = "substrate-application-crypto", path = "../../../application-crypto", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
schnorrkel = { version = "0.8.4", features = ["preaudit_deprecated"], optional = true }
slots = { package = "substrate-consensus-slots", path = "../../slots", optional = true }
sr-primitives = {  path = "../../../sr-primitives", default-features = false }
sr-staking-primitives = { path = "../../../sr-staking-primitives", default-features = false }
substrate-client = { path = "../../../client", default-features = false }

[features]
default = ["std"]
std = [
	"app-crypto/std",
	"codec/std",
	"rstd/std",
	"schnorrkel",
	"slots",
	"sr-primitives/std",
	"sr-staking-primitives/std",
	"substrate-client/std",
]
