[package]
name = "srml-babe"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
app-crypto = { package = "substrate-application-crypto", path = "../../core/application-crypto", default-features = false }
babe-primitives = { package = "substrate-consensus-babe-primitives", path = "../../core/consensus/babe/primitives", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
consensus-common-primitives = { package = "substrate-consensus-common-primitives", path = "../../core/consensus/common/primitives", default-features = false }
inherents = { package = "substrate-inherents", path = "../../core/inherents", default-features = false }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
serde = { version = "1.0.93", optional = true }
session = { package = "srml-session", path = "../session", default-features = false }
balances = { package = "srml-balances", path = "../balances", default-features = false }
indices = { package = "srml-indices", path = "../indices", default-features = false }
sr-io = { path = "../../core/sr-io", default-features = false, features = [ "wasm-nice-panic-message" ] }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
sr-staking-primitives = { path = "../../core/sr-staking-primitives", default-features = false }
srml-support = { path = "../support", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }
timestamp = { package = "srml-timestamp", path = "../timestamp", default-features = false }
hex-literal = "0.2"

[dev-dependencies]
lazy_static = "1.3.0"
parking_lot = "0.9.0"
primitives = { package = "substrate-primitives",  path = "../../core/primitives" }

[features]
default = ["std"]
std = [
	"babe-primitives/std",
	"codec/std",
	"inherents/std",
	"rstd/std",
	"serde",
	"session/std",
	"balances/std",
	"sr-io/std",
	"sr-primitives/std",
	"sr-staking-primitives/std",
	"srml-support/std",
	"system/std",
	"timestamp/std",
]
